version: "3.9"
name: alvearium-web

networks:
    alvearium-web:

services:

    nginx:
        image: nginx:stable
        volumes: 
            - ./html:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        
        depends_on:
            - php
            - db
        networks:
            - alvearium-web

    php:
        build: 
            context: .
            dockerfile: ./Dockerfile-php
        volumes: 
            - ./html:/var/www/html
        ports:
            - 9123:9000
        
        networks:
            - alvearium-web

    db:
        image: mysql:latest
        volumes: 
            - ./db:/var/lib/mysql
        ports:
            - 5123:3306
        
        environment:
            - MYSQL_DATABASE=alvearium-web
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        networks:
            - alvearium-web
